export const ORDER_PRIORITIES = {
  ROUTINE: 'ROUTINE',
  URGENT: 'URGENT',
  STAT: 'STAT',
} as const;
export type OrderPriority = (typeof ORDER_PRIORITIES)[keyof typeof ORDER_PRIORITIES];

export const ORDER_STATUSES = {
  DRAFT: 'DRAFT',
  PENDING_SIGNATURE: 'PENDING_SIGNATURE',
  ORDERED: 'ORDERED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
export type OrderStatus = (typeof ORDER_STATUSES)[keyof typeof ORDER_STATUSES];

export const ORDER_TYPES = {
  LAB: 'LAB',
  IMAGING: 'IMAGING',
  MEDICATION: 'MEDICATION',
  PROCEDURE: 'PROCEDURE',
  REFERRAL: 'REFERRAL',
  DIET: 'DIET',
  NURSING_CARE: 'NURSING_CARE',
} as const;
export type OrderType = (typeof ORDER_TYPES)[keyof typeof ORDER_TYPES];

export const DISPATCH_STATUSES = {
  CREATED: 'CREATED',
  DISPATCHED: 'DISPATCHED',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  ON_HOLD: 'ON_HOLD',
  CANCELLED: 'CANCELLED',
} as const;
export type DispatchStatus = (typeof DISPATCH_STATUSES)[keyof typeof DISPATCH_STATUSES];

export const DISPATCH_TYPES = {
  LAB_SPECIMEN: 'LAB_SPECIMEN',
  PHARMACY_PRESCRIPTION: 'PHARMACY_PRESCRIPTION',
  RADIOLOGY_REQUEST: 'RADIOLOGY_REQUEST',
  PROCEDURE_ROOM_OT: 'PROCEDURE_ROOM_OT',
  WARD_BED_TRANSFER: 'WARD_BED_TRANSFER',
  PATIENT_TRANSPORT: 'PATIENT_TRANSPORT',
  EXTERNAL_REFERRAL: 'EXTERNAL_REFERRAL',
} as const;
export type DispatchType = (typeof DISPATCH_TYPES)[keyof typeof DISPATCH_TYPES];

export const PROCEDURE_CATEGORIES = {
  DIAGNOSTIC: 'DIAGNOSTIC',
  THERAPEUTIC: 'THERAPEUTIC',
  SURGICAL: 'SURGICAL',
  IMAGING: 'IMAGING',
  LABORATORY: 'LABORATORY',
  IMMUNIZATION: 'IMMUNIZATION',
  REHABILITATIVE: 'REHABILITATIVE',
} as const;
export type ProcedureCategory = (typeof PROCEDURE_CATEGORIES)[keyof typeof PROCEDURE_CATEGORIES];

export const PROCEDURE_STATUSES = {
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  ENTERED_IN_ERROR: 'ENTERED_IN_ERROR',
} as const;
export type ProcedureStatus = (typeof PROCEDURE_STATUSES)[keyof typeof PROCEDURE_STATUSES];

export const CLINICAL_NOTE_STATUSES = {
  DRAFT: 'DRAFT',
  SIGNED: 'SIGNED',
  AMENDED: 'AMENDED',
} as const;
export type ClinicalNoteStatus = (typeof CLINICAL_NOTE_STATUSES)[keyof typeof CLINICAL_NOTE_STATUSES];

export const CLINICAL_NOTE_TEMPLATES = {
  SOAP: 'SOAP',
  CONSULTATION: 'CONSULTATION',
  PROCEDURE_NOTE: 'PROCEDURE_NOTE',
  DISCHARGE_SUMMARY: 'DISCHARGE_SUMMARY',
  NURSING_NOTE: 'NURSING_NOTE',
  FREE_TEXT: 'FREE_TEXT',
} as const;
export type ClinicalNoteTemplate = (typeof CLINICAL_NOTE_TEMPLATES)[keyof typeof CLINICAL_NOTE_TEMPLATES];

export const ENCOUNTER_TYPES = {
  OUTPATIENT: 'OUTPATIENT',
  INPATIENT: 'INPATIENT',
  EMERGENCY: 'EMERGENCY',
  TELEHEALTH: 'TELEHEALTH',
} as const;
export type EncounterType = (typeof ENCOUNTER_TYPES)[keyof typeof ENCOUNTER_TYPES];

export const ENCOUNTER_STATUSES = {
  PLANNED: 'PLANNED',
  ARRIVED: 'ARRIVED',
  TRIAGED: 'TRIAGED',
  IN_PROGRESS: 'IN_PROGRESS',
  ON_LEAVE: 'ON_LEAVE',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED',
} as const;
export type EncounterStatus = (typeof ENCOUNTER_STATUSES)[keyof typeof ENCOUNTER_STATUSES];

export const APPOINTMENT_STATUSES = {
  BOOKED: 'BOOKED',
  CONFIRMED: 'CONFIRMED',
  ARRIVED: 'ARRIVED',
  CHECKED_IN: 'CHECKED_IN',
  IN_CONSULTATION: 'IN_CONSULTATION',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
} as const;
export type AppointmentStatus = (typeof APPOINTMENT_STATUSES)[keyof typeof APPOINTMENT_STATUSES];

export const LAB_RESULT_FLAGS = {
  NORMAL: 'N',
  HIGH: 'H',
  LOW: 'L',
  CRITICAL: 'CRIT',
} as const;
export type LabResultFlag = (typeof LAB_RESULT_FLAGS)[keyof typeof LAB_RESULT_FLAGS];

export const INVOICE_STATUSES = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  VOID: 'VOID',
} as const;
export type InvoiceStatus = (typeof INVOICE_STATUSES)[keyof typeof INVOICE_STATUSES];
